-- PURELA PHARMACY POS schema
-- Run this in your Supabase SQL editor.

create table if not exists products (
  id bigint primary key,
  name text not null,
  generic text not null,
  category text not null,
  batch text not null unique,
  stock integer not null check (stock >= 0),
  reorder integer not null check (reorder >= 0),
  expiry date not null,
  price numeric(12, 2) not null check (price > 0),
  prescription boolean not null default false,
  location text not null,
  supplier text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists customers (
  id bigint primary key,
  name text not null,
  phone text not null,
  plan text not null default 'Private pay',
  allergies text not null default 'None recorded',
  last text not null default 'New profile',
  status text not null default 'Ready',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null default 'Cashier' check (role in ('Cashier', 'Pharmacist', 'Manager', 'Admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists prescriptions (
  id text primary key,
  patient_id bigint not null references customers(id) on delete cascade,
  medication_id bigint not null references products(id) on delete cascade,
  status text not null check (status in ('Insurance', 'Clinical check', 'Verified', 'Filled', 'Released')),
  prescriber text not null,
  wait text not null default '00 min',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sales (
  id text primary key,
  patient text not null,
  cashier text not null,
  payment text not null check (payment in ('Cash', 'Transfer', 'POS Card', 'Credit')),
  shift text not null check (shift in ('Morning Shift', 'Afternoon Shift', 'Off Shift')),
  subtotal numeric(12, 2) not null,
  discount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table products enable row level security;
alter table customers enable row level security;
alter table profiles enable row level security;
alter table prescriptions enable row level security;
alter table sales enable row level security;
alter table audit_logs enable row level security;

drop policy if exists "Public POS product access" on products;
create policy "Public POS product access" on products
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public POS customer access" on customers;
create policy "Public POS customer access" on customers
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public POS profile access" on profiles;
create policy "Public POS profile access" on profiles
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public POS prescription access" on prescriptions;
create policy "Public POS prescription access" on prescriptions
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public POS sales access" on sales;
create policy "Public POS sales access" on sales
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public POS audit access" on audit_logs;
create policy "Public POS audit access" on audit_logs
for all to anon, authenticated
using (true)
with check (true);

do $$
begin
  alter publication supabase_realtime add table products;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table customers;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table prescriptions;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table sales;
exception
  when duplicate_object then null;
end $$;

-- Products intentionally start empty. Add your real pharmacy products from the POS Add Product dashboard.

-- Optional: make the existing Supabase Auth user an Admin profile for the POS.
-- This lets the app automatically show Admin features after login.
insert into profiles (id, email, name, role)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'name', 'Nneoma'),
  'Admin'
from auth.users
where email = 'nneoma1@gmail.com'
on conflict (email) do update
set role = 'Admin',
    name = excluded.name,
    updated_at = now();

insert into customers (id, name, phone, plan, allergies, last, status)
values
  (1, 'Grace Miller', '(555) 018-4491', 'Aetna Rx', 'Penicillin', 'New customer profile', 'Due today'),
  (2, 'Daniel Brooks', '(555) 013-9240', 'Private pay', 'None recorded', 'Blood pressure check', 'Ready'),
  (3, 'Maya Chen', '(555) 019-3044', 'BlueCross', 'Sulfa', 'New customer profile', 'Needs consult')
on conflict (id) do nothing;
